-- ARK-40 (design: ARK-39 §2, feature-audit §2.4): accounting module — 표준
-- 계정과목(더존/KcLep 코드)/회계 거래처/전표(복식부기)/은행대사/법인카드. Reuses ARK-10's
-- tenant_id + Postgres RLS pattern verbatim on all 7 tenant-scoped tables (see
-- prisma/migrations/20260701000001_tenant_rls_policies and
-- docs/multi-tenancy.md). `JournalLine` has no RLS of its own, same reason as
-- `OrderItem`/`AccountPriceListEntry` — always reached via its parent
-- `JournalEntry`, which is FORCE ROW LEVEL SECURITY.
--
-- Naming note (ARK-39 §0): the standard chart-of-accounts table is named
-- `LedgerAccount`, not `Account` — `Account` was already taken by ARK-16's B2B
-- 거래처 model. They are deliberately separate entities that don't reference
-- each other; `AccPartner.linkedAccountId` is the optional bridge.
--
-- DDL below (through the AddForeignKey block) was generated by
-- `prisma migrate diff --from-url <applied-state> --to-schema-datamodel
-- prisma/schema.prisma --script` against a PGlite-backed Postgres holding the
-- 4 prior migrations already applied, then hand-reviewed — not hand-written —
-- so it matches prisma/schema.prisma exactly. The GRANT/RLS block below that
-- is added by hand, same as every prior migration in this repo (Prisma has no
-- native RLS support).

-- CreateEnum
CREATE TYPE "LedgerAccountCategory" AS ENUM ('ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE');

-- CreateEnum
CREATE TYPE "AccPartnerType" AS ENUM ('GENERAL', 'CARD', 'BANK');

-- CreateEnum
CREATE TYPE "JournalEntryStatus" AS ENUM ('DRAFT', 'POSTED', 'VOID');

-- CreateEnum
CREATE TYPE "JournalSourceType" AS ENUM ('ORDER_SALE', 'BANK_TRANSACTION', 'CC_TRANSACTION', 'MANUAL');

-- CreateEnum
CREATE TYPE "DebitCredit" AS ENUM ('DEBIT', 'CREDIT');

-- CreateEnum
CREATE TYPE "BankTransactionDirection" AS ENUM ('DEPOSIT', 'WITHDRAWAL');

-- CreateEnum
CREATE TYPE "CcTaxType" AS ENUM ('TAXABLE', 'EXEMPT', 'NON_DEDUCTIBLE', 'UNKNOWN');

-- AlterTable
ALTER TABLE "Order" ADD COLUMN     "partnerId" TEXT,
ADD COLUMN     "partnerName" TEXT;

-- CreateTable
CREATE TABLE "LedgerAccount" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "category" "LedgerAccountCategory" NOT NULL,
    "isSystemLocked" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "LedgerAccount_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AccPartner" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "type" "AccPartnerType" NOT NULL,
    "name" TEXT NOT NULL,
    "businessRegistrationNo" TEXT,
    "bankAccountNo" TEXT,
    "linkedAccountId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "AccPartner_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "JournalEntry" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "entryDate" TIMESTAMP(3) NOT NULL,
    "description" TEXT,
    "status" "JournalEntryStatus" NOT NULL DEFAULT 'POSTED',
    "sourceType" "JournalSourceType" NOT NULL,
    "sourceId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "JournalEntry_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "JournalLine" (
    "id" TEXT NOT NULL,
    "journalEntryId" TEXT NOT NULL,
    "accountId" TEXT NOT NULL,
    "side" "DebitCredit" NOT NULL,
    "amountKrw" INTEGER NOT NULL,
    "partnerId" TEXT,
    "partnerName" TEXT,
    "memo" TEXT,

    CONSTRAINT "JournalLine_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "BankTransaction" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "transactionDate" TIMESTAMP(3) NOT NULL,
    "rawDescription" TEXT NOT NULL,
    "amountKrw" INTEGER NOT NULL,
    "direction" "BankTransactionDirection" NOT NULL,
    "matchedOrderId" TEXT,
    "matchedPaymentId" TEXT,
    "journalEntryId" TEXT,
    "splitLines" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "BankTransaction_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "BankRule" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "matchPattern" TEXT NOT NULL,
    "accountId" TEXT NOT NULL,
    "partnerId" TEXT,
    "priority" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "BankRule_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CcTransaction" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "transactionDate" TIMESTAMP(3) NOT NULL,
    "merchantName" TEXT NOT NULL,
    "amountKrw" INTEGER NOT NULL,
    "sourceHash" TEXT NOT NULL,
    "taxType" "CcTaxType" NOT NULL DEFAULT 'UNKNOWN',
    "merchantMapId" TEXT,
    "journalEntryId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "CcTransaction_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CcMerchantMap" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "merchantNamePattern" TEXT NOT NULL,
    "accountId" TEXT NOT NULL,
    "partnerId" TEXT,
    "defaultTaxType" "CcTaxType" NOT NULL DEFAULT 'TAXABLE',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "CcMerchantMap_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "LedgerAccount_tenantId_category_idx" ON "LedgerAccount"("tenantId", "category");

-- CreateIndex
CREATE UNIQUE INDEX "LedgerAccount_tenantId_code_key" ON "LedgerAccount"("tenantId", "code");

-- CreateIndex
CREATE INDEX "AccPartner_tenantId_type_idx" ON "AccPartner"("tenantId", "type");

-- CreateIndex
CREATE UNIQUE INDEX "AccPartner_tenantId_type_name_key" ON "AccPartner"("tenantId", "type", "name");

-- CreateIndex
CREATE INDEX "JournalEntry_tenantId_entryDate_idx" ON "JournalEntry"("tenantId", "entryDate");

-- CreateIndex
CREATE INDEX "JournalEntry_tenantId_sourceType_sourceId_idx" ON "JournalEntry"("tenantId", "sourceType", "sourceId");

-- CreateIndex
CREATE INDEX "JournalLine_journalEntryId_idx" ON "JournalLine"("journalEntryId");

-- CreateIndex
CREATE INDEX "JournalLine_accountId_idx" ON "JournalLine"("accountId");

-- CreateIndex
CREATE INDEX "BankTransaction_tenantId_transactionDate_idx" ON "BankTransaction"("tenantId", "transactionDate");

-- CreateIndex
CREATE INDEX "BankTransaction_tenantId_matchedOrderId_idx" ON "BankTransaction"("tenantId", "matchedOrderId");

-- CreateIndex
CREATE INDEX "BankRule_tenantId_priority_idx" ON "BankRule"("tenantId", "priority");

-- CreateIndex
CREATE INDEX "CcTransaction_tenantId_transactionDate_idx" ON "CcTransaction"("tenantId", "transactionDate");

-- CreateIndex
CREATE UNIQUE INDEX "CcTransaction_tenantId_sourceHash_key" ON "CcTransaction"("tenantId", "sourceHash");

-- CreateIndex
CREATE INDEX "CcMerchantMap_tenantId_idx" ON "CcMerchantMap"("tenantId");

-- AddForeignKey
ALTER TABLE "Order" ADD CONSTRAINT "Order_partnerId_fkey" FOREIGN KEY ("partnerId") REFERENCES "AccPartner"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LedgerAccount" ADD CONSTRAINT "LedgerAccount_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Seller"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AccPartner" ADD CONSTRAINT "AccPartner_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Seller"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AccPartner" ADD CONSTRAINT "AccPartner_linkedAccountId_fkey" FOREIGN KEY ("linkedAccountId") REFERENCES "Account"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "JournalEntry" ADD CONSTRAINT "JournalEntry_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Seller"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "JournalLine" ADD CONSTRAINT "JournalLine_journalEntryId_fkey" FOREIGN KEY ("journalEntryId") REFERENCES "JournalEntry"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "JournalLine" ADD CONSTRAINT "JournalLine_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "LedgerAccount"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "JournalLine" ADD CONSTRAINT "JournalLine_partnerId_fkey" FOREIGN KEY ("partnerId") REFERENCES "AccPartner"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BankTransaction" ADD CONSTRAINT "BankTransaction_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Seller"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BankTransaction" ADD CONSTRAINT "BankTransaction_matchedOrderId_fkey" FOREIGN KEY ("matchedOrderId") REFERENCES "Order"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BankTransaction" ADD CONSTRAINT "BankTransaction_journalEntryId_fkey" FOREIGN KEY ("journalEntryId") REFERENCES "JournalEntry"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BankRule" ADD CONSTRAINT "BankRule_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Seller"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BankRule" ADD CONSTRAINT "BankRule_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "LedgerAccount"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BankRule" ADD CONSTRAINT "BankRule_partnerId_fkey" FOREIGN KEY ("partnerId") REFERENCES "AccPartner"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CcTransaction" ADD CONSTRAINT "CcTransaction_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Seller"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CcTransaction" ADD CONSTRAINT "CcTransaction_merchantMapId_fkey" FOREIGN KEY ("merchantMapId") REFERENCES "CcMerchantMap"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CcTransaction" ADD CONSTRAINT "CcTransaction_journalEntryId_fkey" FOREIGN KEY ("journalEntryId") REFERENCES "JournalEntry"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CcMerchantMap" ADD CONSTRAINT "CcMerchantMap_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Seller"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CcMerchantMap" ADD CONSTRAINT "CcMerchantMap_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "LedgerAccount"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CcMerchantMap" ADD CONSTRAINT "CcMerchantMap_partnerId_fkey" FOREIGN KEY ("partnerId") REFERENCES "AccPartner"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- ARK-10 pattern reused verbatim (ARK-39 §3): least-privilege role grant +
-- RLS on each new tenant-scoped table. `arkain_app` already exists (created
-- by the ARK-10 migration). Only does anything once the app connects as that
-- non-superuser, non-BYPASSRLS role — see docs/multi-tenancy.md.

GRANT SELECT, INSERT, UPDATE, DELETE ON
  "LedgerAccount", "AccPartner", "JournalEntry", "JournalLine",
  "BankTransaction", "BankRule", "CcTransaction", "CcMerchantMap"
TO arkain_app;

ALTER TABLE "LedgerAccount" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LedgerAccount" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "LedgerAccount"
  USING ("tenantId" = current_setting('app.tenant_id', true))
  WITH CHECK ("tenantId" = current_setting('app.tenant_id', true));

ALTER TABLE "AccPartner" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AccPartner" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "AccPartner"
  USING ("tenantId" = current_setting('app.tenant_id', true))
  WITH CHECK ("tenantId" = current_setting('app.tenant_id', true));

ALTER TABLE "JournalEntry" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "JournalEntry" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "JournalEntry"
  USING ("tenantId" = current_setting('app.tenant_id', true))
  WITH CHECK ("tenantId" = current_setting('app.tenant_id', true));

ALTER TABLE "BankTransaction" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BankTransaction" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "BankTransaction"
  USING ("tenantId" = current_setting('app.tenant_id', true))
  WITH CHECK ("tenantId" = current_setting('app.tenant_id', true));

ALTER TABLE "BankRule" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BankRule" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "BankRule"
  USING ("tenantId" = current_setting('app.tenant_id', true))
  WITH CHECK ("tenantId" = current_setting('app.tenant_id', true));

ALTER TABLE "CcTransaction" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CcTransaction" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "CcTransaction"
  USING ("tenantId" = current_setting('app.tenant_id', true))
  WITH CHECK ("tenantId" = current_setting('app.tenant_id', true));

ALTER TABLE "CcMerchantMap" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CcMerchantMap" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "CcMerchantMap"
  USING ("tenantId" = current_setting('app.tenant_id', true))
  WITH CHECK ("tenantId" = current_setting('app.tenant_id', true));

-- `JournalLine` deliberately has no RLS policy of its own (ARK-39 §3) — same
-- reason as `OrderItem`/`AccountPriceListEntry`: always reached via its
-- parent `JournalEntry`, which is FORCE ROW LEVEL SECURITY.
